@startuml
    participant Alice
    participant Auth
    participant RoomController
    participant RoomService
    participant RoomRepository
    participant Database

    Alice->Auth: DELETE /api/rooms
    note over Alice, Auth : Authorization: Bearer <access_token>
    
    Auth-->Auth: Verify token
    alt invalid token
        Auth --> Alice: 401: Ban khong co quyen thuc hien hanh dong nay
    else valid token
        Auth -> RoomController: Forward request with validated token
    
        RoomController->>RoomService: deleteRoom(ids)
        RoomService->>RoomService: validateRoomData(ids)
        alt invalid data 
            RoomService-->>RoomController: Return 400 error
            RoomController-->>Alice: 400: Du lieu gui len khong hop le
        else valid data
            RoomService->>RoomRepository: deleteRoom(ids)
            RoomRepository->>Database: DELETE Room data
            Database-->>RoomRepository: Confirm delete
            RoomRepository-->>RoomService: Return success
            RoomService-->>RoomController: Return success
            RoomController-->>Alice: 200: Delete Room thanh cong
        end
    end
@enduml